apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: myapp-dev
  labels:
    app: backend
    tier: web
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: backend
    tier: web
    environment: dev
  ports:
    - port: 8000
      targetPort: 8000
