apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp-dev
  labels:
    app: backend
    tier: web
    environment: dev
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: web
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        tier: web
        environment: dev
    spec:
      containers:
        - image: aks-backend:v1.0.0 
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          # readinessProbe:            
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:               
          #   httpGet:
          #     path: /
          #     port: 8000
          #   initialDelaySeconds: 10
            # periodSeconds: 30
      restartPolicy: Always
