apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - args:
            - python
            - consumer.py
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
          image: consumer
          name: consumer
      restartPolicy: Always
