apiVersion: v1
kind: Service
metadata:
  namespace: myapp-dev   
  name: redis
  labels:
    app: redis
    tier: web
    environment: dev
spec:
  type: NodePort  
  selector:
    app: redis
    tier: web
    environment: dev
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31010
