apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp-dev
  labels:
    app: mongodb
    tier: web
    environment: dev
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: web
      environment: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        tier: web
        environment: dev
    spec:
      containers:
        - image: mongo:6.0
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 30

      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
