# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: mongodb
#     tier: web
#     environment: dev
#   name: mongodb
# spec:
#   type: NodePort                     
#   selector:
#     app: mongodb
#     tier: web
#     environment: dev
#   ports:
#     - port: 27017
#       targetPort: 27017
#       nodePort: 31000

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
    tier: web
    environment: dev
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
    tier: web
    environment: dev
  ports:
    - port: 27017
      targetPort: 27017
