apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: {{ .Values.backend.name }}
    tier: {{ .Values.backend.tier }}
    environment: {{ .Values.backend.environment }}
spec:
  type: {{ .Values.backend.serviceType }} 
  selector:
    app: {{ .Values.backend.name }}
    tier: {{ .Values.backend.tier }}
    environment: {{ .Values.backend.environment }}
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.targetPort }}
      nodePort: {{ .Values.frontend.nodePort }}
