apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  labels:
    app: {{ .Values.mongodb.name }}
    tier: {{ .Values.mongodb.tier }}
    environment: {{ .Values.environment }}
spec:
  type: {{ .Values.mongodb.serviceType }}
  selector:
    app: {{ .Values.mongodb.name }}
    tier: {{ .Values.mongodb.tier }}
    environment: {{ .Values.environment }}
  ports:
    - port: {{ .Values.mongodb.servicePort }}
      targetPort: {{ .Values.mongodb.targetPort }}
      nodePort: {{ .Values.mongodb.nodePort }}
