apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: myapp-dev
  labels:
    app: frontend
    tier: web
    environment: dev
spec:
  type: ClusterIP              
  selector:
    app: frontend
    tier: web
    environment: dev
  ports:
    - port: 80            
      targetPort: 80
