apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myapp-dev             
  labels:
    app: rabbitmq
    tier: web
    environment: dev
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      tier: web
      environment: dev
  template:
    metadata:
      labels:
          app: rabbitmq
          tier: web
          environment: dev
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      restartPolicy: Always
