apiVersion: v1
kind: Service
metadata:
  namespace: myapp-dev
  labels:
    app: rabbitmq
    tier: web
    environment: dev
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
    tier: web
    environment: dev
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 32010
      name: amqp-1
    - port: 5672
      targetPort: 5672
      nodePort: 32020
      name: amqp-2
